name: Flutter CI

on:
  push:
    branches:
      - main   # Trigger workflow when code is pushed to the 'main' branch
  pull_request:
    branches:
      - main   # Trigger workflow on pull requests to the 'main' branch

jobs:
  flutter-build:
    runs-on: ubuntu-latest  # Running the workflow on Ubuntu

    steps:
      - name: check the system tree
        run: cd /;tree
